name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Build Golang application
      run: go build -o myapp

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Push Docker image to Azure Container Registry
      run: |
        docker build -t myapp .
        docker tag myapp gulmallbackend.azurecr.io/myapp:latest
        docker login gulmallbackend.azurecr.io -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
        docker push gulmallbackend.azurecr.io/myapp:latest

    - name: Deploy to Azure Web App
      run: az webapp deployment container config --name gulmallbackend --resource-group <your-resource-group> --container-image <your-azure-container-registry-name>.azurecr.io/myapp:latest