name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
permissions:
      id-token: write
      contents: read
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag paktradebackend
      
    - name: Azure Login
      uses: azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }} 
       
 #   - name: Azure Container Registery Login
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: paktradebackend.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t paktradebackend.azurecr.io/myapp:${{ github.sha }}
        docker push mycontainer.azurecr.io/myapp:${{ github.sha }}      
   # - name: Docker Tag
    #  run: docker tag paktradebackend paktradebackend.azurecr.io/paktradebackend
    #- name: Docker Push
     # run: docker push paktradebackend.azurecr.io/paktradebackend
      
