name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Build Docker
      run: docker build -t go-backend-app .
    - name: Az Login
      run: az acr login -n paktradebackend --expose-token
    - name: Docker Tag
      run: docker tag go-backend-app gobackendapp1.azurecr.io/go-backend-app
    - name: Docker Push
      run: docker push gobackendapp1.azurecr.io/go-backend-app
      
